apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      params:
      - name: IMAGE
        value: harbor.ci-stack.caas/demo/hello-world-app:$PULL_NUMBER
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go-plugin/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: "git-clone"
          resources: {}
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: "make-lint"
          resources: {}
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: "build-make-linux"
          resources: {}
          script: |
            #!/bin/sh
            go build ./...
        - image: uses:tektoncd/catalog/task/kaniko/0.3/kaniko.yaml@HEAD
          name: ""
          resources: {}
