apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/go/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 600Mi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: git-clone
          resources: {}
        - name: make-lint
          resources: {}
        - name: "build-make-linux"
          resources: {}
          script: |
            #!/bin/sh
            go build -o main cmd/hello-world/main.go
        - image: gcr.io/kaniko-project/executor:v1.6.0-debug
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            author=$(git show -s --pretty=%an)
            /kaniko/executor $KANIKO_FLAGS --context=/workspace/source --dockerfile=${DOCKERFILE_PATH:-Dockerfile} --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$author-$VERSION
          env:
          - name: PUSH_CONTAINER_REGISTRY
            value: harbor.ci-stack.caas
          - name: DOCKER_REGISTRY_ORG
            value: demo
          - name: APP_NAME
            value: hello-world-app
          - name: VERSION
            value: $(params.PULL_NUMBER)
          - name: KANIKO_FLAGS 
            value: --skip-tls-verify
  serviceAccountName: build-bot
  timeout: 12h0m0s
