# (C) Copyright 2019 Hewlett Packard Enterprise Development LP
#
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  deadline: 6m
  skip-files:
    - ".*[Mm]ock.*\\.go$"
  tests: true
  build-tags:
     - test

linters-settings:
  govet:
    check-shadowing: true
    settings:
      composites:
        whitelist: true
  goimports:
    local-prefixes: github.com/hpe-hcss
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true

    # [deprecated] comma-separated list of pairs of the form pkg:regex
    # the regex is used to ignore names within pkg. (default "fmt:.*").
    # see https://github.com/kisielk/errcheck#the-deprecated-method for details
    ignore: fmt:.*,io/ioutil:^Read.*,go.uber.org/zap:.*Sync

    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    # exclude: /path/to/file.txt
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 20
linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - gosimple
    - golint
    - govet
    - goconst
    - ineffassign
    - misspell
    - unconvert
    - unused
    - unparam
    - nakedret
    - errcheck
    - varcheck
    - staticcheck
    - gochecknoinits

issues:
  exclude-use-default: false
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
      - govet
      - ineffassign
      - unused
      - errcheck
      - staticcheck
      - goconst

  max-per-linter: 0
  max-same-issues: 0
  new: false
